name: Dev CD

on:
  release:
    types: [created]
      # you may add other branches to
      # activate deployment for them, too.

jobs:
  check_semantic_tag_format:
    runs-on: ubuntu-latest
    outputs:
      # export to be used in other jobs
      tag_name: ${{ steps.tag_name.outputs.tag_name }}
      branch: ${{ steps.tag_name.outputs.branch }}
    steps:
      - uses: actions/checkout@v3
        name: Check out code

      - name: Get tag name
        id: tag_name
        run: |
          BRANCH="$(git rev-parse --abbrev-ref HEAD)"
          TAG_NAME="$(git describe --tags --abbrev=0)"
          echo "tag: $TAG_NAME"
          echo ::set-output name=tag_name::$TAG_NAME
          echo "branch: $BRANCH"
          echo ::set-output name=branch::$BRANCH

      - name: Check tag format
        id: check_semantic_tag_format
        run: |
          SEMVER_REGEX="^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(\-[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?(\+[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$"
          if echo "${{ steps.tag_name.outputs.tag_name }}" | grep -Eq "$SEMVER_REGEX"; then
            echo "Tag format is valid"
          else
            echo "Invalid tag format: ${{ steps.tag_name.outputs.tag_name }}"
            exit 1
          fi

  check_python_package_version:
    runs-on: ubuntu-latest
    needs: check_semantic_tag_format
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Check package version matches tag
        run: |
          PACKAGE_VERSION=$(python setup.py --version)
          if [[ "$PACKAGE_VERSION" == "${{ needs.check_semantic_tag_format.outputs.tag_name }}" ]]; then
            echo "Package version matches tag"
          else
            echo "Package version $PACKAGE_VERSION does not match tag ${{ needs.check_semantic_tag_format.outputs.tag_name }}"
            exit 1
          fi

  push_to_docker_hub:
    runs-on: ubuntu-latest
    needs: check_semantic_tag_format
    steps:
      - uses: actions/checkout@v3
        name: Check out code

      - uses: docker/setup-qemu-action@v2.0.0
        name: Set up QEMU

      - uses: docker/setup-buildx-action@v2.0.0
        name: Set up Docker Buildx

      - uses: docker/login-action@v2.0.0
        name: Login to DockerHub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v3.0.0
        name: Build and push
        id: docker_build
        with:
          push: true
          #       platforms: linux/amd64,linux/arm64/v8
          tags: "ghga/${{ github.event.repository.name }}:${{ needs.check_semantic_tag_format.outputs.tag_name }},ghga/${{ github.event.repository.name }}:${{ needs.check_semantic_tag_format.outputs.branch }}"

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "docker.io/ghga/${{ github.event.repository.name }}:${{ needs.check_semantic_tag_format.outputs.tag_name }}"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  ## Please uncomment and adapt the DEPLOYMENT_CONFIG_REPO to trigger automatic
  ## updates of helm charts:
  # update_deployment_repo:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - check_semantic_tag_format
  #     - push_to_docker_hub
  #   env:
  #     DEPLOYMENT_CONFIG_REPO: ghga-de/helm
  #   steps:
  #     - name: trigger update in deployment repo
  #       run: |
  #         # access token needs to be of format: <username>:<personal_access_token>
  #         curl -X POST \
  #           "https://api.github.com/repos/${DEPLOYMENT_CONFIG_REPO}/dispatches" \
  #           -H 'Accept: application/vnd.github.everest-preview+json' \
  #           -u '${{ secrets.DEPLOYMENT_UPDATE_TOKEN }}' \
  #           --data '{
  #             "event_type": "new_app_version",
  #             "client_payload": {
  #               "deploy_filename": "${{ github.event.repository.name }}",
  #               "app_name": "${{ github.event.repository.name }}",
  #               "context": "${{ needs.check_semantic_tag_format.outputs.branch }}",
  #               "new_image_tag": "${{ needs.check_semantic_tag_format.outputs.version }}"
  #             }
  #           }'
